name: Example build with custom image

on:
  push:
    branches: [ master ]
  
env:
  REGISTRY: quay.io
  IMAGE_NAME: samu_pusila_cgi/actions-example-using-custom-docker 

jobs:
  build-binary: 
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/samopus/actions-custom-image-build:2.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_DOCKER_REGISTRY }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Checkout External Repository TEST
      uses: actions/checkout@v3
      with:
        repository: https://github.com/fmidev/iris_to_hdf5.git
    - name: Build Binary
      run: ./build.sh
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: example-build-package
        path: package.zip

  build-and-push-image:
    needs: build-binary
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: example-build-package
    - name: Prepare Docker Image
      run: unzip package.zip
    - name: Login to Docker Image Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_SECRET }}
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: latest
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      
  test-image:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    container:
      image: quay.io/samu_pusila_cgi/actions-example-using-custom-docker:latest
      credentials:
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_SECRET }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    - name: Run tests
      run: ./test.sh

