name: Example build with custom image

on:
  push:
    branches: [ master ]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: actions-custom-iamge-runtime

jobs:
  build-binary:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/samopus/actions-custom-image-build:2.5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_DOCKER_REGISTRY }}
    steps:
    - uses: actions/checkout@v3
    - name: Build Binary
      run: ./build.sh

  build-and-push-image:
    needs: build-binary
    runs-on: ubuntu-latest
    steps:
    - name: Login to Github Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_DOCKER_REGISTRY }}
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
